import { documentHtml, brand } from "./ui.js";
export const consoleHtml = documentHtml(
  `
<div class="review-shell"><header class="topbar">${brand}<span class="chip neutral">Verification workspace</span></header>
<div class="page-heading"><div><div class="eyebrow">Capability operations</div><h1>Evidence you can inspect.</h1><p>Validate a release, review its results, and replay with confidence.</p></div><span id="connection" class="chip neutral">Connecting</span></div>
<p id="notice" role="status" aria-live="polite">Open the private console URL printed by the server.</p>
<div class="review-grid"><section class="main-panel"><h2>Release lifecycle</h2><p>Candidate → validated → approved → active. Approval requires the complete 38-case matrix.</p><label for="release">Workflow version</label><select id="release"></select><p id="release-status"></p>
<div class="actions"><button id="validate" disabled>Validate 38 scenarios</button><button id="approve" disabled>Approve release</button><button id="activate" disabled>Activate release</button><button id="rollback" disabled>Roll back to this version</button></div>
<details><summary>Review artifact and changes</summary><pre id="artifact"></pre><pre id="diff"></pre></details>
<details id="candidate-tools"><summary>Add a candidate version</summary><label for="version">New version</label><input id="version" placeholder="1.1.0" pattern="[0-9]+\\.[0-9]+\\.[0-9]+"><button id="copy">Copy selected as candidate</button><label for="import">Or import a discovered capability JSON</label><input type="file" id="import" accept=".json,application/json"></details>
</section><section class="main-panel"><h2>Run a scenario</h2><p>Only the active approved release can run. All records are synthetic.</p><label for="member">Member number</label><input id="member" inputmode="numeric" maxlength="5" placeholder="5 digits (e.g. 12345)" value="12345"><label for="variant">Application layout</label><select id="variant"><option value="classic">Classic table workspace</option><option value="cards">Card workspace with renamed labels</option></select><label for="scenario">Scenario</label><select id="scenario"></select><button id="run" disabled>Run approved workflow</button><p id="run-help">Validate, approve and activate a release first.</p></section></div>
<section class="main-panel evidence-panel"><div class="row"><h2>Execution evidence</h2><span id="job-status" class="chip neutral">No run selected</span></div><label for="jobs">Recent jobs</label><select id="jobs"></select><progress id="progress" max="1" value="0"></progress><div id="metrics" class="review-metrics"></div><p id="result"></p><div id="validation-runs"></div><ol id="timeline" aria-label="Execution timeline"></ol><details><summary>Saved redacted run record</summary><pre id="record"></pre></details></section>
<section class="main-panel evidence-panel"><h2>Release audit</h2><ol id="history"></ol></section><footer class="footer-note">Local synthetic sandbox. Model calls are counted at the provider boundary. Session recovery scenarios use an automated operator stand-in. No model is permitted during replay.</footer></div><script src="/console.js"></script>`,
  "",
  "Ledger | Capability verification",
).replace(
  "</style>",
  `
.review-shell{max-width:1320px;margin:auto;padding:24px}.review-grid{display:grid;grid-template-columns:1.3fr 1fr;gap:20px}.review-shell .main-panel{border:1px solid #dce5f1;border-radius:18px;background:white;padding:26px;min-width:0}.review-shell label{display:block;font-weight:600;margin:16px 0 7px}.review-shell select,.review-shell input{width:100%;padding:12px;border:1px solid #b9c8dc;border-radius:8px;font:inherit;min-width:0}.review-shell button{margin:10px 8px 8px 0}.review-shell .actions{display:flex;flex-wrap:wrap}.review-shell pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#f4f7fb;padding:14px;max-height:360px;overflow:auto;font-size:12px}.evidence-panel{margin-top:20px}#timeline{max-height:480px;overflow:auto;padding-right:12px}.review-metrics{display:flex;gap:14px;flex-wrap:wrap}.review-metrics span{background:#f1f6ff;border-radius:10px;padding:14px}.review-shell progress{width:100%;height:14px;margin:18px 0}.review-shell #timeline li,.review-shell #history li{padding:9px 0;border-bottom:1px solid #e5ebf2;overflow-wrap:anywhere}.review-shell #notice{padding:14px;border-radius:10px;background:#eaf2ff}.review-shell #validation-runs{max-height:240px;overflow:auto}.review-shell details{margin-top:16px}.review-shell summary{cursor:pointer;font-weight:600}.review-shell .row{justify-content:space-between;flex-wrap:wrap}@media(max-width:800px){.review-grid{grid-template-columns:1fr}.review-shell{padding:14px}.review-shell h1{font-size:30px}.review-shell .main-panel{padding:18px}} </style>`,
);

export const consoleScript = String.raw`'use strict';
const token=location.hash.slice(1);history.replaceState(null,'',location.pathname);
const $=id=>document.getElementById(id);let state={releases:[],active:{},history:[]};let role='runner';let selectedJob='';let selectedRun='';let running=false;let sending=false;let lastJobState='';
const labels={normal:'Successful lookup',not_found:'Member not found',validation:'Application validation',notice:'Service notice',transient:'Temporary outage',slow:'Slow loading',session:'Session expired — stop',handoff:'Session recovery — automated operator',permission:'Permission denied',app_error:'Application error',unknown_dialog:'Unexpected dialog',ambiguous:'Ambiguous target',wrong_member:'Wrong member on summary',bad_output:'Invalid balance output',drift:'Incompatible search screen',drift_late:'Incompatible summary screen',injection:'Untrusted page instructions',recovery_exhausted:'Recovery limit reached'};
for(const [value,label] of Object.entries(labels))$('scenario').add(new Option(label,value));
async function api(route,body){const response=await fetch('/api/'+route,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const value=await response.json();if(!response.ok)throw new Error(value.code||'REQUEST_FAILED');return value;}
function message(text){$('notice').textContent=text;}
function release(){return state.releases.find(r=>r.artifact.id+'@'+r.artifact.version===$('release').value);}
function gate(){const r=release();const blocked=running||sending;const admin=role==='reviewer';$('validate').disabled=!admin||blocked||!r||r.status==='approved';$('approve').disabled=!admin||blocked||r?.status!=='validated';$('activate').disabled=!admin||blocked||r?.status!=='approved'||state.active[r?.artifact.id]===r?.artifact.version;$('rollback').disabled=!admin||blocked||r?.status!=='approved'||state.active[r?.artifact.id]===r?.artifact.version||!state.history.some(h=>h.event==='activate'&&h.id===r?.artifact.id&&h.version===r?.artifact.version);$('run').disabled=blocked||!Object.keys(state.active).length||!/^[0-9]{5}$/.test($('member').value);$('copy').disabled=!admin||blocked||!r||!/^d{1,6}.d{1,6}.d{1,6}$/.test($('version').value);$('import').disabled=!admin||blocked;$('release-status').textContent=r?'Status: '+r.status+(state.active[r.artifact.id]===r.artifact.version?' · active':'')+' · SHA-256 '+r.digest.slice(0,16):'No release available';$('run-help').textContent=Object.keys(state.active).length?'The active approved version will run; other versions remain unchanged.':'Validate, approve and activate a release first.';$('artifact').textContent=r?JSON.stringify(r.artifact,null,2):'';const active=state.releases.find(x=>x.artifact.id===r?.artifact.id&&x.artifact.version===state.active[r?.artifact.id]);$('diff').textContent=active&&r?JSON.stringify({activeVersion:active.artifact.version,candidateVersion:r.artifact.version,stepsChanged:JSON.stringify(active.artifact.steps)!==JSON.stringify(r.artifact.steps),changedFields:Object.keys(r.artifact).filter(key=>JSON.stringify(active.artifact[key])!==JSON.stringify(r.artifact[key])),before:active.artifact,after:r.artifact},null,2):'No active release to compare.';}
async function refresh(){if(role==='reviewer')state=await api('releases');else{const caps=await api('capabilities');state={releases:caps.map(c=>({artifact:c,status:'approved',digest:c.digest})),active:Object.fromEntries(caps.map(c=>[c.id,c.version])),history:[]};}const prior=$('release').value;$('release').replaceChildren();for(const r of state.releases)$('release').add(new Option(r.artifact.id+' · '+r.artifact.version,r.artifact.id+'@'+r.artifact.version));if([...$('release').options].some(o=>o.value===prior))$('release').value=prior;$('history').replaceChildren();for(const h of state.history.slice(-20).reverse()){const li=document.createElement('li');li.textContent=h.event+' · '+h.id+' '+h.version+' · '+h.at;$('history').append(li);}gate();}
async function transact(task){if(sending||running)return;sending=true;gate();try{await task();await refresh();}catch(e){message(e.message);}finally{sending=false;gate();}}
for(const action of ['validate','approve','activate','rollback'])$(action).onclick=()=>transact(async()=>{const r=release();const result=await api('releases/'+action,{id:r.artifact.id,version:r.artifact.version});if(action==='validate'){selectedJob=result.id;selectedRun='';running=true;message('Validation is running. All 38 cases must pass before approval.');}else message(action==='rollback'?'Previous approved version restored.':action==='approve'?'Release approved. Activate it when ready.':'Release activated.');});
$('copy').onclick=()=>transact(async()=>{const artifact=structuredClone(release().artifact);artifact.version=$('version').value;await api('releases/import',artifact);message('New immutable candidate added. It requires its own validation and approval.');});
$('import').onchange=()=>transact(async()=>{const file=$('import').files[0];if(!file)return;if(file.size>65536)throw new Error('BODY_TOO_LARGE');await api('releases/import',JSON.parse(await file.text()));message('Candidate imported.');});
$('run').onclick=()=>transact(async()=>{const id=Object.keys(state.active)[0];const job=await api('invoke',{id,memberId:$('member').value,variant:$('variant').value,scenario:$('scenario').value});selectedJob=job.id;selectedRun='';running=true;message('Running the approved workflow. Watch its checkpoints below.');});
for(const id of ['member','version'])$(id).oninput=gate;$('release').onchange=gate;$('jobs').onchange=()=>{selectedJob=$('jobs').value;selectedRun='';};
function renderRun(run){$('record').textContent=JSON.stringify(run,null,2);$('metrics').replaceChildren();const metrics=run.metrics;if(metrics)for(const [label,value] of [['Model calls',metrics.modelCalls],['Recovery attempts',metrics.recoveryAttempts],['Actions',metrics.actions],['Duration (ms)',metrics.durationMs]]){const span=document.createElement('span');span.textContent=label+': '+value;$('metrics').append(span);}$('result').textContent=run.result?'Outcome: '+run.result.status+(run.result.code?' · '+run.result.code:''):'Execution in progress';$('timeline').replaceChildren();for(const e of run.events){const li=document.createElement('li');li.textContent=[e.at,e.event,e.step,e.target?.name,e.expected,e.reason,e.passed===true?'verified':'',e.actor].filter(Boolean).join(' · ');$('timeline').append(li);}}
async function poll(){try{const jobs=await api('jobs');running=jobs.some(j=>j.status==='running');$('jobs').replaceChildren();for(const job of jobs.slice().reverse())$('jobs').add(new Option(job.kind+' · '+job.status+' · '+job.id.slice(0,8),job.id));if(!selectedJob&&jobs.length)selectedJob=jobs[jobs.length-1].id;$('jobs').value=selectedJob;const job=jobs.find(j=>j.id===selectedJob);if(job){$('job-status').textContent=job.kind+' · '+job.status;$('progress').max=job.total;$('progress').value=job.progress;if(lastJobState!==job.id+job.status){lastJobState=job.id+job.status;if(job.code)message(job.code);else if(job.kind==='replay'&&job.status==='complete')message('Run complete. Inspect the outcome and saved evidence below.');else if(job.kind==='validation'&&job.status==='complete')message(job.result.validation.passed?'Validation passed. Review the evidence before approving.':'Validation failed. This candidate cannot be approved.');}if(job.runId)selectedRun=job.runId;const ids=job.result?.validation?.runIds??[];if($('validation-runs').dataset.job!==job.id+job.status){$('validation-runs').dataset.job=job.id+job.status;$('validation-runs').replaceChildren();ids.forEach((id,index)=>{const button=document.createElement('button');button.textContent='Inspect trial '+(index+1);button.onclick=()=>{selectedRun=id;};$('validation-runs').append(button);});}if(selectedRun)renderRun(await api('runs/'+selectedRun));}await refresh();}catch(e){message(e.message);}finally{setTimeout(poll,1000);}}
(async()=>{try{role=(await api('session')).role;$('connection').textContent=role==='reviewer'?'Reviewer session':'Runner session';$('candidate-tools').hidden=role!=='reviewer';message('Connected. Tokens stay in memory and are removed from the address bar.');await refresh();poll();}catch(e){message('Unable to connect: '+e.message+'. Use the private URL from the running server.');}})();
`;
